#! /bin/sh

# config.sh.in 

# This file is processed by config.status to produce config.status,
# containing autoconf-determined values needed by the test scripts.

ECHO_T=""
ECHO_N="-n"
ECHO_C=""

export ECHO_T ECHO_N ECHO_C
