#
# Makefile for the linux pmfs-filesystem routines.
#

obj-$(CONFIG_PMFS_FS) += pmfs.o

pmfs-y := bbuild.o balloc.o dir.o file.o inode.o namei.o super.o symlink.o ioctl.o pmfs_stats.o journal.o xip.o wprotect.o

#CFLAGS_nvmm_perfmodel.o := -mhard-float -Og
#CFLAGS_bbuild.o := -mhard-float -Og
#CFLAGS_balloc.o := -mhard-float -Og
#CFLAGS_dir.o := -mhard-float -Og
#CFLAGS_file.o := -mhard-float -Og
#CFLAGS_inode.o := -mhard-float -Og
#CFLAGS_namei.o := -mhard-float -Og
#CFLAGS_super.o := -mhard-float -Og
#CFLAGS_symlink.o := -mhard-float -Og
#CFLAGS_ioctl.o := -mhard-float -Og
#CFLAGS_pmfs_stats.o := -mhard-float -Og
#CFLAGS_journal.o := -mhard-float -Og
#CFLAGS_xip.o := -mhard-float -Og
#CFLAGS_wprotect.o := -mhard-float -Og
